name: rspl_network_file_viewer
description: "RSPLNetworkFileViewer is a customizable Flutter widget for displaying network images and PDFs with flexible UI, headers, and error handling."
version: 1.0.0
license: LicenseRef-Rishabh-Software-Non-Commercial-1.0
homepage: https://github.com/rishabhsoftwarepvtltd/FlutterNetworkFileViewer
repository: https://github.com/rishabhsoftwarepvtltd/FlutterNetworkFileViewer

environment:
  sdk: '>=3.4.0 <4.0.0'

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  easy_image_viewer: ^1.5.1
  flutter_cached_pdfview: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
